# Generated by Django 5.1.7 on 2025-09-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kyc_verified',
            field=models.BooleanField(default=False),
        ),
    ]
