# Generated by Django 5.2.6 on 2025-09-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_listing_listingdocument_listingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='fractionalisation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='let_agent_suggest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='ownership_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='tax_certificate',
            field=models.FileField(blank=True, null=True, upload_to='listing_docs/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='title_deed',
            field=models.FileField(blank=True, null=True, upload_to='listing_docs/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='utility_bills',
            field=models.FileField(blank=True, null=True, upload_to='listing_docs/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
