# Generated by Django 5.2.6 on 2025-09-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_listing_bedrooms_listing_fractionalisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='metadata_cid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
